name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GITHUB_WORKSPACE: /home/runner/work/multi-docker/multi-docker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build docker image
        run: |
          docker build -t anr35/react-test -f ./client/Dockerfile.dev ./client
      - name: run tests for react app
        run: |
          docker run -e CI=true anr35/react-test npm test -- --coverage
  upload_image_to_docker_hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: build images
        run: |
          docker build -t anr35/multi-client ./client
          docker build -t anr35/multi-nginx ./nginx
          docker build -t anr35/multi-server ./server
          docker build -t anr35/multi-worker ./worker
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_ID}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: push to docker hub
        run: |
          docker push anr35/multi-client
          docker push anr35/multi-nginx
          docker push anr35/multi-server
          docker push anr35/multi-worker
